### ISSUE TITLE
index.SearchForFacetValue: Unknown parameter: requests

### ISSUE THREAD

**Issue by barnesoir** [algolia/algoliasearch-client-csharp#547]
- Algolia Client Version: 6.0.2
- Language Version: C#

### Description
Whenever using SearchForFacetValue a 400 error is returned saying:
`Algolia.Search.Exceptions.AlgoliaApiException: {"message":"Unknown parameter: requests","status":400}`
### Steps To Reproduce
On any index query and existing or none existing facet (both work fine on older client)
Code taken from docs:
`

                var queryParams = new Query
                {
                    Filters = "brand:Apple"
                };

                var x = _index.SearchForFacetValue(new SearchForFacetRequest
                {
                    FacetName = "phone",
                    FacetQuery = "category",
                    SearchParameters = queryParams
                });

`

**Comment by Ant-hem** [comment]
Hello 👋 

Thanks for your contribution.

You're right. There is an error in `SearchForFacetRequest.cs` the `SearchParameters` property should have a `[JsonProperty(PropertyName = "params")]` instead of ` [JsonProperty(PropertyName = "requests")]`. 

I'll submit a PR to fix it today, then I'll publish a new version of the library soon because we have new feature to ship. I'll ping you when it's shipped.

**Comment by barnesoir** [comment]
Perfect, thank you for the speedy response.

**Comment by Ant-hem** [comment]
Solved with [6.1.0](https://www.nuget.org/packages/Algolia.Search/6.1.0)
