### ISSUE TITLE
NBPages not returning true result

### ISSUE THREAD

**Issue by barnesoir** [algolia/algoliasearch-client-csharp#557]
- Algolia Client Version: 6.1.1
- Language Version: .net core 2.2

### Description
Pagination doesn't work correctly, for example when a query returns 7000 hits and a page size of 100 there should be 70 pages, however I'm only getting 10.

### Steps To Reproduce
`var searchResponse = _index.Search<object>(new Query
                {
                    SearchQuery = searchTest,
                    Filters = filterString,
                    HitsPerPage = 100,
                    Page = 0
                });`

According to the docs:
Calculation is based on the total number of hits (nbHits) divided by the number of hits per page (hitsPerPage), however I'm getting nbHits = 7204 and hitsPerPage = 100 so I should be getting 73 pages. When I try and access page 11 I get no results despite there being more data.

**Comment by Ant-hem** [comment]
Hi!

Without more information regarding your records and your settings, I see two possible reasons that could explain the page count can be incoherent with the number of hits:

- You are searching over an index where `distinct` is enabled. In this case, the number of hits that you will get will be larger than the number of pages because you will only display a single record for distinct value, while the number of hits is still equal to the number of records. This possibility is the most likely reason for the mismatch.
- You are exhausting the performance budget of the query, and the engine returns an approximation of the number of hits. If that is the case, the boolean `exhaustiveNbHits` will be set to false in the response. This can happen when using complex filters.

If it's not one of the two points above and you don't want to share your settings information here, you can contact our [support team](https://www.algolia.com/support/) mentioning this issue and asks for a personification of your index.

**Comment by barnesoir** [comment]
exhaustiveNbHits is true in the response and the items are all unique.

**Comment by barnesoir** [comment]
Index settings were not being set correctly, no issue with code.
