### ISSUE TITLE
Optional filters are not working

### ISSUE THREAD

**Issue by mykhailo-rednikin** [algolia/algoliasearch-client-csharp#560]
- Algolia Client Version: 6.1.1
- Language Version: .NET Core 2.2

### Description

optional filters are not working

### Steps To Reproduce

optional filters setup is as follows:

            query.OptionalFilters = new IEnumerable<string>[]
            {
                new string[] { "numericField=5"},
                new string[] { "numericField=4"},
                new string[] { "numericField=3"}
            };

results ordering doesn't reflect that setup.

**Comment by Ant-hem** [comment]
Hi!

If we look at the [documentation](https://www.algolia.com/doc/guides/managing-results/refine-results/merchandising-and-promoting/how-to/how-to-promote-with-optional-filters/#optional-filters) regarding `optionalFilters`, by design you can't do numeric comparison with it.

>  The optionalFilters parameter only applies on exact matches, you can’t do numeric comparisons like with filters. Therefore, you need to alter your dataset so you can match on exact values.

It's explaining how you can alter dataset to match on exact values.

**Comment by Ant-hem** [comment]
@mykhailo-rednikin any update on this one?

**Comment by mykhailo-rednikin** [comment]
Thank you! You were absolutely right. Another issue we are experiencing is the unexpected results ordering with optional filter setup for multiple facet fields with custom scores. sumOrFiltersScores is on. With single field all works as expected. But with multiple it produces weird results. It is definitely not and API issue. Thank you for your time!
