### ISSUE TITLE
`SearchIndex.DeleteObjectsAsync` throws a `ArgumentNullException` when the argument is an empty collection.

### ISSUE THREAD

**Issue by SaxJ** [algolia/algoliasearch-client-csharp#731]
- Algolia Client Version: 6.6.0
- Language Version: 3.1.7

### Description
`SearchIndex.DeleteObjectsAsync` throws a `ArgumentNullException` when the argument is an empty collection.

### Steps To Reproduce
```
var searchClient = new SearchClient("foo", "bar");
var index = searchClient.InitIndex("my_index");
var task = index.DeleteObjectsAsync(new List<string>());

await task;
```
You will see `DeleteObjectsAsync` throws an `ArgumentNullException`

**Comment by Ant-hem** [comment]
Hey @SaxJ 

This behavior is expected see [this part of the code.](https://github.com/algolia/algoliasearch-client-csharp/blob/73449dac238022ac7f8b4313e53c64ea56cf26a9/src/Algolia.Search/Clients/SearchIndex.cs#L349-L355)  For the record, this check is there to prevent users to delete their whole index. In fact, months (years?) ago, an empty list sent to the API could lead to the deletion of all the records (can you confirm @aseure?) . I am not sure it's still the case. 

Was this your use-case? If so you could use the `clearObjects` method.

**Comment by Ant-hem** [comment]
> My main issue is the type of the exception thrown. It doesn't make sense to throw an `ArgumentNullException` when an empty collection is passed. I think instead it should:
> 
>     * throw a `ArgumentException` with a more descriptive error message, OR
> 
>     * Just return a `Task.CompletedTask` if an empty collection is passed.

Yes fair enough, we can enhance the message being return I 100% agree with you. The other solutions you mentioned are great as well but they would be breaking API for the current `6.X versions` and we try to avoid as much as possible to break the public API for our libraries.

I'll open an issue later today describing the expected changes, feel free to tackle it if you are willing to contribute to the library.

**Comment by aseure** [comment]
Thanks for reporting this @SaxJ. As described by @Ant-hem I confirm that passing an empty array of objects would effectively clear the index, hence the thrown exception.

Regarding the possible solutions, here are my two cents:

 - even though the `ArgumentNullException` should probably have been an `ArgumentException` instead, I think we should keep it this way to prevent breaking user-code
 - I'd probably vote against the `Task.CompletedTask` since this will probably confuse users thinking an actual call was made to the API, wherease we were actually faking it, and this will not be visible from their dashboard/logs

As for the next steps, I'd agree with @Ant-hem: let's fix this my improving the error message of the thrown `ArgumentException`.

WDYT @SaxJ?

**Comment by SaxJ** [comment]
Improving the error message sounds like a good solution with constraints on backwards compatibility. :+1:
