### ISSUE TITLE
Calling Index.Delete().Wait() throws null reference exception.

### ISSUE THREAD

**Issue by MingLu8** [algolia/algoliasearch-client-csharp#757]
Calling Index.Delete().Wait() throws null reference exception.

**Comment by Ant-hem** [comment]
Hello,

Indeed, I was able to reproduce the issue locally.

Here is the fix that should be written:

The following method in order to be waitable

https://github.com/algolia/algoliasearch-client-csharp/blob/1d62daefc81f2883d9a817337faa37ad100a39bc/src/Algolia.Search/Clients/SearchIndex.cs#L368-L374

Should follow the same pattern as this one:

https://github.com/algolia/algoliasearch-client-csharp/blob/1d62daefc81f2883d9a817337faa37ad100a39bc/src/Algolia.Search/Clients/SearchIndex.cs#L381-L396

To test that we could add a call to this function in one of the e2e tests of 
`src/Algolia.Search.Test/EndToEnd/Index/IndexingTest.cs`

Would you like to work on a fix? If not we'll take of it.

**Comment by TomKlotzPro** [comment]
Hey @MingLu8, the fix has been done ! I hope you will like it :)
