### ISSUE TITLE
index.BrowseFrom(...) result

### ISSUE THREAD

**Issue by ToineSeiter** [algolia/algoliasearch-client-csharp#80]
Hello,

I'm using the nuget package Algolia.Search 3.6.5 and Newtonsoft.Json 9.0.1

`index.BrowseFrom(query, cursor)` returns a JObject containing only the following fields : 
- cursor
- hits
- params
- processingTimeMS
- query

If I make a CURL request, I see more data like : 
- nbHits
- page
- nbPages
- hitsPerPage
- query

How can I get these fileds ?
It would be nice to have a complete JObject result.

I need to know how many pages are returned to build a pager for SEO purpose.

**Comment by CBaptiste** [comment]
Hello @ToineSeiter !
I will have a look and keep you posted !

**Comment by clement-leprovost** [comment]
Following our recent conversation with @ToineSeiter on Algolia's Live Chat, it turns out that the difference is actually due the presence of a filter in one case. When a filter is specified, the API cannot know in advance the number of hits. It can when there are no filters, since it's just the total number of objects in the index, and provides this information as a convenience. However, you should not rely on it. The nominal way of browsing an index is to pass the last returned cursor until the API returns no cursor, meaning that the browse is finished.
