### ISSUE TITLE
[🔔 Announcement 🔔] New client - looking for early feedback! 

### ISSUE THREAD

**Issue by morganleroi** [algolia/algoliasearch-client-csharp#852]
Hello ! 👋🏼 

We have just [released a new major client](https://www.nuget.org/packages/Algolia.Search/7.0.0-alpha.0) version (7.0-alpha).

This version has been completely rewritten and is part of the [Api Automation Initiative](https://github.com/algolia/api-clients-automation), which means that models and routes are generated from the [Algolia APIs Specifications](https://github.com/algolia/api-clients-automation/tree/main/specs).

This release introduces major changes. A document has been created to help you migrate from v6 to v7. You can find it [here](https://api-clients-automation.netlify.app/docs/clients/migration-guides/).

We want to hear from you! This alpha release is not intended for production use, but the best way for us to move forward with this new client is to get direct feedback from you!

If you want to test this new version in your codebase, do not hesitate to open issues to give us insights / bugs / feedback.

Thanks a lot for your help 🙇🏼

**Comment by AdTarling** [comment]
Observations:
 - The strongly typed versions of the search response don't seem to respect JsonProperty decorators anymore, ie the property names have to match the Algolia property names which is a pretty significant breaking change.
 - The Recommend API no longer seems to have strongly typed versions of the get methods
 - The documentation for version 7 is far too light at present

**Comment by SebastianStehle** [comment]
I just tried to migrate. In the old version I was passing a JRaw object, because it was already serialized. Is there a counterpart to that?

**Comment by fredericDelaporte** [comment]
> The strongly typed versions of the search response don't seem to respect JsonProperty decorators anymore, ie the property names have to match the Algolia property names which is a pretty significant breaking change.

That is an undocumented breaking change for the C# library: they have switched from Newtonsoft.Json to Sytem.Text.Json for serializing the objects. So any `Newtonsoft.Json` annotation done on models are broken. They need to be migrated to their `System.Text.Json` counterpart annotation.

(@AdTarling)

**Comment by SebastianStehle** [comment]
What is about my JRaw? It is relatively easy to implement with a custom converter and it would be great to accept serialized objects: https://learn.microsoft.com/en-us/dotnet/api/system.text.json.utf8jsonwriter.writerawvalue?view=net-6.0

An alternative could be to pass a JsonSerializerOptions.

Btw:
I think your whole infrastructure for HttpClient is not really needed. You should also not create a static client: https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/http/httpclient-guidelines#recommended-use

In my opinion, it would be best to support IHttpClientFactory and get rid of all the extra code. HttpClient provides everything already and with HttpClientFactory you can also inject extra behavior, for example retries, default timeouts and so on.

**Comment by fredericDelaporte** [comment]
There is another breaking change about JSON serialization we have seen later: the `System.Text.Json` serialization is set in the Algolia client to convert enums to string, while previously, they were converted to integers.

Since the Algolia client registers a global converter for doing this, it seems the only ways to adapt is either to set a custom converter on all enum properties of serialized models, or type the enum properties as `int` and adapt the code fetching them.

**Comment by lee-m** [comment]
Unfortunately v7 seems to a big step backwards in usability of the C# client. In my application I have a relatively small index of a few thousand records which gets regenerated when the source data changes. In v6 this is very simple using `SearchIndex.ReplaceAllObjectsAsync`.

In v7 there is no such thing and trying to check the documentation doesn't help as it's not been updated for the v7 changes ([here for example](https://www.algolia.com/doc/api-reference/api-methods/replace-all-objects/))

In trying to figure out a migration path for this (since the migration guide doesn't make any mention of this) by digging through the v6 code, I can see that in v6 `ReplaceAllObjectsAsync` simply indexes the new objects in a temporary index and then uses [MoveIndex](https://www.algolia.com/doc/api-reference/api-methods/move-index/) to replace the live index with the temporary one.

Buy yet again, there is no "MoveIndex" method to be found anywhere.  When I look at the [new docs page](https://www.algolia.com/doc/rest-api/search/#tag/Indices/operation/operationIndex) page, what used to be a simple 

```
var client = new SearchClient(new SearchConfig("YOUR_APP_ID", "YOUR_API_KEY"));
var index = client.InitIndex("destination");

await index.MoveFromAsync("source");
```

Appears to now be

```
var response = await client.OperationIndexAsync(
  "<SOURCE_INDEX_NAME>",
  new OperationIndexParams
  {
    Operation = Enum.Parse<OperationType>("Move"),
    Destination = "<DESTINATION_INDEX_NAME>",
    Scope = new List<ScopeType>
    {
      Enum.Parse<ScopeType>("Rules"),
      Enum.Parse<ScopeType>("Settings")
    },
  }
);
```

That is a not a good change IMO and this is only one operation that directly affects my application. I've also found something similar in trying to figure out the new way batch indexing multiple objects in a single go and that also seems to be equally unwieldy in v7 now.

**Comment by morganleroi** [comment]
If you have any questions or issues with the new `v7`, please [open an issue](https://github.com/algolia/algoliasearch-client-csharp/issues).

**Comment by AdTarling** [comment]
What about Recommend, I don't see any strongly typed versions of the get methods any longer.  There's a response object that needs to be manipulated, rather than specifying the record object to automatically deserialize to?  If that's a known issue please add as well.
